## SPARQL query to select a table of the data catalogue content

PREFIX t:     <https://schema.coypu.org/metadata-template#>
PREFIX dcat:  <http://www.w3.org/ns/dcat#>
PREFIX dct:   <http://purl.org/dc/terms/>
PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?Dataset 
  (GROUP_CONCAT(DISTINCT ?Type_ ; separator=" / ") AS ?Type)
  (SAMPLE(?Theme_) AS ?Theme)
WHERE {
	?s a t:Dataset ;
		dct:identifier ?Dataset_ ;
	bind(concat("[", ucase(?Dataset_), "](", str(?s), ")") AS ?Dataset) .
	OPTIONAL { ?s t:type ?Type_ } .
	OPTIONAL { ?s t:theme ?Theme_ } .
}
GROUP BY ?Dataset
ORDER BY ?Dataset
